---

- hosts: all
  gather_facts: True
  remote_user: ubuntu

  pre_tasks:
    - name: Install git
      become: yes
      become_user: root
      become_method: sudo
      package:
        name: git
        state: present

    - name: Include group variables
      include_vars:
        file: group_vars/all
        name: group_vars

  tasks:
    - name: Checkout the git reporsitory of this project
      remote_user: ubuntu
      git:
        repo: https://github.com/HarishAtGitHub/Jsplumb-Matching
        dest: /home/ubuntu/hello

