---
- name: Install basic required packed apache curl
  become: yes
  become_user: root
  become_method: sudo
  package:
    name : "{{ item }}"
    state: present
  with_items:
    - curl
    - apache2
    - nodejs

- name: Transfer the key
  copy:
    src: "{{ group_vars.repository_key }}"
    dest: "{{ group_vars.remote_repository_key_location }}"
    mode: 0600

  #- name: see variable
  #debug:
  #  msg: "{{ group_vars.remote_repository_key_location }}/{{ group_vars.remote_repository_key_name }}"

- name: Checkout the git repository of this project
  remote_user: ubuntu
  git:
    repo: "{{ group_vars.repository_url }}"
    dest: "{{ group_vars.web_repo_checkout_location }}"
    key_file: "{{ group_vars.remote_repository_key }}"
    accept_hostkey: yes
